services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./.dev.env
    depends_on:
      - db
      - redis
    networks:
      - default

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - ./.dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    networks:
      - default

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: